// ============================================
// GENOVA — Frontend connected to Supabase
// ============================================

const SUPABASE_URL = window.GENOVA_CONFIG?.SUPABASE_URL
const SUPABASE_KEY = window.GENOVA_CONFIG?.SUPABASE_KEY
if (!SUPABASE_URL || !SUPABASE_KEY) {
  throw new Error('Missing Genova frontend configuration.')
}
const db = supabase.createClient(SUPABASE_URL, SUPABASE_KEY)

let currentUser = null
let currentProject = null
let authMode = 'login'
let pendingOtpEmail = ''
let projects = []
let currentFiles = []
let selectedFilePath = ''
let genRunning = false
let agentMessages = []
let agentChannel = null

const AI_MODEL_LABELS = {
  'gpt-5-4-mini': 'GPT-5.4 Mini',
  'gpt-5-4': 'GPT-5.4',
  'claude-haiku-4-5': 'Claude Haiku 4.5',
  'claude-sonnet-4-6': 'Claude Sonnet 4.6',
  'claude-opus-4-8': 'Claude Opus 4.8',
  'claude-fable-5': 'Claude Fable 5'
}

function enterAgentMode(){document.body.classList.add('agent-mode');const genTab=document.querySelector('[data-tab="generate"]');if(genTab)switchTab(genTab)}
function exitAgentMode(){document.body.classList.remove('agent-mode')}

async function initAuth() {
  ensureAgentPanel()
  const { data: { session } } = await db.auth.getSession()
  if (session) { currentUser = session.user; onSignedIn() }
  else { document.getElementById('authOverlay').classList.remove('hidden'); showAuthForm() }
  db.auth.onAuthStateChange((event, session) => {
    if (event === 'SIGNED_IN' && session) { currentUser = session.user; onSignedIn() }
    if (event === 'SIGNED_OUT') { currentUser = null; exitAgentMode(); closeAgentPanel(); document.getElementById('authOverlay').classList.remove('hidden'); showAuthForm() }
  })
}
function setAuthMode(mode){authMode=mode;showAuthForm();const signupFields=document.getElementById('signupProfileFields');if(signupFields)signupFields.classList.toggle('hidden',mode!=='signup');document.getElementById('authTabLogin').classList.toggle('active',mode==='login');document.getElementById('authTabSignup').classList.toggle('active',mode==='signup');document.getElementById('authSubmit').textContent=mode==='login'?'Sign in':'Create account';document.getElementById('authPassword').autocomplete=mode==='login'?'current-password':'new-password';document.getElementById('authError').style.color='var(--red)';document.getElementById('authError').textContent=''}
function showAuthForm(){document.getElementById('authFormView')?.classList.remove('hidden');document.getElementById('otpFormView')?.classList.add('hidden');const s=document.getElementById('authSubtitle');if(s)s.textContent='Sign in or create your workspace to start building.'}
function showOtpForm(email){pendingOtpEmail=email;document.getElementById('authFormView')?.classList.add('hidden');document.getElementById('otpFormView')?.classList.remove('hidden');document.getElementById('otpEmailLabel').textContent=email;const s=document.getElementById('authSubtitle');if(s)s.textContent='Security verification';const input=document.getElementById('otpCode');if(input){input.value='';setTimeout(()=>input.focus(),80)}const e=document.getElementById('otpError');if(e){e.style.color='var(--text2)';e.textContent='The code expires after a few minutes.'}}
function backToAuthForm(){pendingOtpEmail='';showAuthForm();setAuthMode(authMode)}
async function submitAuth(){const email=document.getElementById('authEmail').value.trim().toLowerCase();const password=document.getElementById('authPassword').value;const errorEl=document.getElementById('authError');errorEl.style.color='var(--red)';errorEl.textContent='';if(!email||!password){errorEl.textContent='Email and password are required.';return}const btn=document.getElementById('authSubmit');btn.disabled=true;btn.textContent='Loading...';try{let result;if(authMode==='signup'){const firstName=document.getElementById('signupFirstName')?.value.trim()||'';const lastName=document.getElementById('signupLastName')?.value.trim()||'';const company=document.getElementById('signupCompany')?.value.trim()||'';const displayName=[firstName,lastName].filter(Boolean).join(' ');result=await db.auth.signUp({email,password,options:{data:{first_name:firstName,last_name:lastName,company,display_name:displayName||email}}});if(result.error)errorEl.textContent=translateError(result.error.message);else if(result.data.session){currentUser=result.data.user;onSignedIn()}else{showOtpForm(email);showToast('Confirmation code sent')}}else{result=await db.auth.signInWithPassword({email,password});if(result.error)errorEl.textContent=translateError(result.error.message)}}catch(e){errorEl.textContent='Server connection error.';console.error(e)}btn.disabled=false;btn.textContent=authMode==='login'?'Sign in':'Create account'}
async function verifyOtpCode(){const code=document.getElementById('otpCode').value.replace(/\D/g,'').slice(0,6);const errorEl=document.getElementById('otpError');const btn=document.getElementById('otpSubmit');errorEl.style.color='var(--red)';errorEl.textContent='';if(!pendingOtpEmail){errorEl.textContent='Email not found. Please sign up again.';return}if(code.length!==6){errorEl.textContent='Enter the 6-digit code.';return}btn.disabled=true;btn.textContent='Verifying...';try{const{data,error}=await db.auth.verifyOtp({email:pendingOtpEmail,token:code,type:'signup'});if(error)errorEl.textContent=translateError(error.message);else if(data.session){currentUser=data.user;pendingOtpEmail='';showToast('Email confirmed. Welcome to Genova!');onSignedIn()}else{errorEl.style.color='var(--teal-light)';errorEl.textContent='Email confirmed. You can now sign in.';setTimeout(()=>backToAuthForm(),1200)}}catch(e){errorEl.textContent='Unable to verify code.';console.error(e)}btn.disabled=false;btn.textContent='Verify code'}
async function resendOtpCode(){const errorEl=document.getElementById('otpError');const btn=document.getElementById('otpResend');if(!pendingOtpEmail){errorEl.style.color='var(--red)';errorEl.textContent='Email not found. Please sign up again.';return}btn.disabled=true;btn.textContent='Sending...';try{const{error}=await db.auth.resend({type:'signup',email:pendingOtpEmail});if(error)errorEl.textContent=translateError(error.message);else{errorEl.style.color='var(--teal-light)';errorEl.textContent='New code sent.';showToast('New code sent')}}catch(e){errorEl.textContent='Unable to resend code.';console.error(e)}btn.disabled=false;btn.textContent='Resend code'}
function translateError(msg){const map={'Invalid login credentials':'Invalid email or password.','User already registered':'An account already exists with this email.','Password should be at least 6 characters.':'Password must be at least 6 characters.','Email not confirmed':'Confirm your email before signing in.','Token has expired or is invalid':'The code is expired or invalid.','Email rate limit exceeded':'Too many requests. Please wait before requesting another code.','Signup requires a valid password':'The password is not valid.','Unable to validate email address: invalid format':'Invalid email format.'};return map[msg]||msg}
async function signOut(){await db.auth.signOut();projects=[];currentProject=null;exitAgentMode();closeAgentPanel();showToast('Signed out')}
async function onSignedIn(){document.getElementById('authOverlay').classList.add('hidden');let initials=getInitialsFromUser(currentUser);const{data:profile}=await db.from('profiles').select('first_name,last_name,display_name').eq('id',currentUser.id).maybeSingle();if(profile)initials=getInitialsFromProfile(profile)||initials;document.getElementById('avatarBtn').textContent=initials;loadProjects()}
function getInitialsFromUser(user){const meta=user?.user_metadata||{};const fromName=[meta.first_name,meta.last_name].filter(Boolean).map(v=>String(v).trim()[0]).join('');return fromName?fromName.toUpperCase().slice(0,2):(user?.email||'??').slice(0,2).toUpperCase()}
function getInitialsFromProfile(profile){const n=[profile.first_name,profile.last_name].filter(Boolean).map(v=>String(v).trim()[0]).join('');if(n)return n.toUpperCase().slice(0,2);if(profile.display_name)return String(profile.display_name).slice(0,2).toUpperCase();return''}

async function loadProjects(){const{data,error}=await db.from('projects').select('*').order('updated_at',{ascending:false});if(error){showToast('Could not load projects');console.error(error);return}projects=data||[];renderSidebar();if(projects.length>0&&!currentProject)setCurrentProject(projects[0])}
function renderSidebar(){const recentEl=document.getElementById('projectListRecent'),favEl=document.getElementById('projectListFav');recentEl.innerHTML='';favEl.innerHTML='';if(projects.length===0){recentEl.innerHTML='<div class="proj-empty">No projects yet — create your first one.</div>';return}const icons={web:'ti-browser',mobile:'ti-device-mobile',fullstack:'ti-layout-grid'};const dots={deployed:'green',building:'amber',planning:'amber',coding:'amber',capturing:'amber',analyzing:'amber',deploying:'amber',draft:'gray',failed:'gray'};projects.forEach(p=>{const item=document.createElement('div');item.className='project-item'+(currentProject&&currentProject.id===p.id?' active':'');item.innerHTML=`<i class="ti ${icons[p.app_type]||'ti-layout'}"></i><span class="project-item-name">${escapeHtml(p.name)}</span><span class="status-dot ${dots[p.status]||'gray'}"></span>`;item.onclick=()=>setCurrentProject(p);(p.is_favorite?favEl:recentEl).appendChild(item)});document.getElementById('favLabel').style.display=projects.some(p=>p.is_favorite)?'block':'none'}
function setCurrentProject(p){currentProject=p;document.getElementById('projectName').textContent=p.name;const labels={deployed:'Deployed',building:'Building',planning:'Planning',coding:'Coding',capturing:'Capturing',analyzing:'Analyzing',deploying:'Deploying',draft:'Draft',failed:'Failed'};const badge=document.querySelector('.project-badge');badge.textContent=labels[p.status]||p.status;badge.className='project-badge'+(p.status==='deployed'?' deployed':'');document.getElementById('deployUrl').textContent=p.deploy_url||'not deployed yet';if(p.initial_prompt)document.getElementById('promptInput').value=p.initial_prompt;if(p.metadata?.model_choice&&document.getElementById('modelChoice'))document.getElementById('modelChoice').value=p.metadata.model_choice;renderSidebar();loadIterations(p.id);loadGeneratedFiles(p.id)}
async function createProject(){const name=document.getElementById('newProjectName').value.trim()||'New project';const typeEl=document.querySelector('.type-option.active-type span');const typeMap={Web:'web',Mobile:'mobile','Full-stack':'fullstack'};const appType=typeMap[typeEl?typeEl.textContent:'Web']||'web';const{data,error}=await db.from('projects').insert({name,app_type:appType,owner_id:currentUser.id}).select().single();if(error){showToast('Could not create project');console.error(error);return}closeNewProject();projects.unshift(data);setCurrentProject(data);showToast(`Project "${name}" created`)}
async function loadIterations(projectId){const{data,error}=await db.from('iterations').select('*').eq('project_id',projectId).order('version',{ascending:false});if(error){console.error(error);return}renderIterations(data||[])}
function renderIterations(iterations){const list=document.querySelector('.iterations-list'),count=document.querySelector('.iter-count');if(!list)return;count.textContent=`${iterations.length} iteration${iterations.length>1?'s':''}`;if(iterations.length===0){list.innerHTML='<div class="proj-empty">No iterations yet — run a generation.</div>';return}list.innerHTML=iterations.map((it,idx)=>`<div class="iteration-card ${idx===0?'active-iter':''}"><div class="iter-meta"><span class="iter-badge ${idx===0?'current':''}">${idx===0?'Current':'v'+it.version}</span><span class="iter-time">${formatDate(it.created_at)}</span></div><div class="iter-prompt">"${escapeHtml(it.prompt)}"</div><div class="iter-result"><span class="result-ok"><i class="ti ti-check"></i> ${it.files_changed||0} files changed</span>${it.visual_score?`<span class="iter-score"><i class="ti ti-eye"></i> Visual score: ${Math.round(it.visual_score)}%</span>`:''}${it.agent_notes?`<span class="iter-score"><i class="ti ti-brain"></i> ${escapeHtml(it.agent_notes.split(':')[0])}</span>`:''}</div></div>`).join('')}
async function loadGeneratedFiles(projectId){const{data,error}=await db.from('generated_files').select('*').eq('project_id',projectId).order('file_path',{ascending:true});if(error){console.error(error);return}currentFiles=data||[];renderFileTree(currentFiles);if(currentFiles.length>0)showFile(currentFiles[0].file_path)}
function renderFileTree(files){const tree=document.querySelector('.file-tree');if(!tree)return;if(!files.length){tree.innerHTML='<div class="file-tree-header">Files</div><div class="proj-empty">No generated files yet.</div>';return}tree.innerHTML='<div class="file-tree-header">Files</div>'+files.map(f=>`<div class="file-item ${f.file_path===selectedFilePath?'active':''}" onclick="showFile('${escapeHtml(f.file_path)}')"><i class="ti ${fileIcon(f.file_path)}"></i> ${escapeHtml(f.file_path)}</div>`).join('')}
function showFile(path){const file=currentFiles.find(f=>f.file_path===path);if(!file)return;selectedFilePath=path;document.querySelectorAll('.file-item').forEach(el=>el.classList.toggle('active',el.textContent.trim()===path));document.getElementById('codeFileName').innerHTML=`<i class="ti ${fileIcon(file.file_path)}"></i> ${escapeHtml(file.file_path)}`;document.getElementById('codeBlock').textContent=file.content||''}
function fileIcon(path){if(path.endsWith('.json'))return'ti-json';if(path.endsWith('.css'))return'ti-file-type-css';if(path.endsWith('.html'))return'ti-file-type-html';if(path.endsWith('.md'))return'ti-markdown';if(path.endsWith('.jsx')||path.endsWith('.tsx'))return'ti-file-type-jsx';return'ti-file'}

function ensureAgentPanel(){if(document.getElementById('agentPanel'))return;const right=document.querySelector('.generate-right');if(!right)return;const panel=document.createElement('div');panel.className='agent-panel';panel.id='agentPanel';panel.innerHTML=`<div class="agent-header"><div class="agent-title"><i class="ti ti-sparkles"></i><span>Genova Agent</span></div><div class="agent-model" id="agentModelLabel">Waiting</div></div><div class="agent-messages" id="agentMessages"><div class="agent-empty">Run a generation to open the agent chat.</div></div>`;right.prepend(panel)}
function openAgentPanel(modelLabel){ensureAgentPanel();document.getElementById('agentPanel')?.classList.add('open');if(modelLabel)document.getElementById('agentModelLabel').textContent=modelLabel}
function closeAgentPanel(){document.getElementById('agentPanel')?.classList.remove('open');if(agentChannel){db.removeChannel(agentChannel);agentChannel=null}}
async function loadAgentMessages(iterationId){if(!iterationId)return;const{data,error}=await db.from('agent_messages').select('*').eq('iteration_id',iterationId).order('created_at',{ascending:true});if(error){console.error(error);return}agentMessages=data||[];renderAgentMessages()}
function subscribeAgentMessages(iterationId){if(agentChannel){db.removeChannel(agentChannel);agentChannel=null}agentChannel=db.channel('agent_messages_'+iterationId).on('postgres_changes',{event:'INSERT',schema:'public',table:'agent_messages',filter:`iteration_id=eq.${iterationId}`},payload=>{agentMessages.push(payload.new);renderAgentMessages()}).subscribe()}
function renderAgentMessages(){ensureAgentPanel();const el=document.getElementById('agentMessages');if(!el)return;if(!agentMessages.length){el.innerHTML='<div class="agent-empty">The agent is preparing...</div>';return}el.innerHTML=agentMessages.map(m=>{const cls=m.type==='error'?'error':m.type==='success'?'success':m.role==='tool'?'tool':m.role==='user'?'user':'assistant';const icon=m.role==='user'?'👤':m.role==='tool'?'⚙️':m.type==='success'?'✅':m.type==='error'?'⚠️':'🤖';return `<div class="agent-msg ${cls}"><div class="agent-avatar">${icon}</div><div class="agent-bubble"><div class="agent-msg-title">${escapeHtml(m.title||roleLabel(m.role,m.type))}</div><div class="agent-msg-content">${escapeHtml(m.content||'')}</div><div class="agent-time">${formatTime(m.created_at)}</div></div></div>`}).join('');el.scrollTop=el.scrollHeight}
function roleLabel(role,type){if(type==='success')return'Success';if(type==='error')return'Error';if(role==='tool')return'Action';if(role==='user')return'You';return'Genova'}

const steps=['plan','code','capture','vision','deploy'];const stepLabels=['Planning the app...','Generating React code...','Saving generated files...','Scoring visual quality...','Finalizing workspace...'];let stepTimer=null
function animatePipeline(){let i=0;steps.forEach(s=>{const el=document.getElementById('step-'+s);if(el)el.dataset.state='idle'});const label=document.getElementById('pipelineLabel');const dot=document.getElementById('pipelineDot');dot.className='pipeline-status-dot running';clearInterval(stepTimer);stepTimer=setInterval(()=>{steps.forEach((s,idx)=>{const el=document.getElementById('step-'+s);if(!el)return;el.dataset.state=idx<i?'done':idx===i?'active':'idle'});label.textContent=stepLabels[Math.min(i,stepLabels.length-1)];i=Math.min(i+1,steps.length-1)},1100)}
function finishPipeline(modelLabel){clearInterval(stepTimer);steps.forEach(s=>{const el=document.getElementById('step-'+s);if(el)el.dataset.state='done'});document.getElementById('pipelineLabel').textContent=`Generation completed with ${modelLabel||'AI'} ✓`;document.getElementById('pipelineDot').className='pipeline-status-dot done'}
function failPipeline(message){clearInterval(stepTimer);document.getElementById('pipelineLabel').textContent=message||'Generation failed';document.getElementById('pipelineDot').className='pipeline-status-dot'}
async function startGeneration(){if(genRunning)return;if(!currentProject){showToast('Create or select a project first');return}const prompt=document.getElementById('promptInput').value.trim();if(!prompt){showToast('Describe your app before generating');return}const modelChoice=document.getElementById('modelChoice')?.value||'gpt-5-4-mini';const modelLabel=AI_MODEL_LABELS[modelChoice]||modelChoice;genRunning=true;enterAgentMode();openAgentPanel(modelLabel);agentMessages=[];renderAgentMessages();const btn=document.getElementById('generateBtn');btn.classList.add('running');btn.innerHTML=`<i class="ti ti-loader"></i> ${modelLabel}...`;const nextVersion=await getNextVersion(currentProject.id);document.getElementById('pipelineIter').textContent=`Iteration #${nextVersion} · ${modelLabel}`;animatePipeline();const{data:iteration,error}=await db.from('iterations').insert({project_id:currentProject.id,owner_id:currentUser.id,version:nextVersion,prompt,status:'queued'}).select().single();if(error){console.error(error);showToast('Could not create iteration');failPipeline('Could not create iteration');resetGenerateButton();return}subscribeAgentMessages(iteration.id);await loadAgentMessages(iteration.id);const{data,error:fnError}=await db.functions.invoke('generate-app',{body:{project_id:currentProject.id,iteration_id:iteration.id,prompt,app_type:currentProject.app_type,model_choice:modelChoice}});if(fnError||data?.error){console.error(fnError||data.error);showToast('Generation failed');failPipeline(data?.error||fnError?.message);resetGenerateButton();await loadIterations(currentProject.id);await loadAgentMessages(iteration.id);return}currentFiles=data.files||[];renderFileTree(currentFiles);if(currentFiles.length)showFile(currentFiles[0].file_path);finishPipeline(data.model_label||modelLabel);currentProject.status='deployed';btn.classList.remove('running');btn.innerHTML='<i class="ti ti-wand"></i> Regenerate';genRunning=false;await loadProjects();await loadIterations(currentProject.id);await loadGeneratedFiles(currentProject.id);await loadAgentMessages(iteration.id);showToast(`Generated ${data.files_changed||currentFiles.length} files with ${data.model_label||modelLabel}`)}
function resetGenerateButton(){const btn=document.getElementById('generateBtn');btn.classList.remove('running');btn.innerHTML='<i class="ti ti-wand"></i> Generate';genRunning=false}
async function getNextVersion(projectId){const{data}=await db.from('iterations').select('version').eq('project_id',projectId).order('version',{ascending:false}).limit(1);return data&&data.length>0?data[0].version+1:1}
function switchTab(el){document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));el.classList.add('active');document.getElementById('tab-'+el.dataset.tab).classList.add('active');if(el.dataset.tab==='iterations'&&currentProject)loadIterations(currentProject.id);if(el.dataset.tab==='code'&&currentProject)loadGeneratedFiles(currentProject.id)}
function switchPreview(el,type){document.querySelectorAll('.preview-tab').forEach(t=>t.classList.remove('active'));el.classList.add('active');document.getElementById('previewWeb').classList.toggle('active',type==='web');document.getElementById('previewMobile').classList.toggle('active',type==='mobile')}
function selectFile(el,name){showFile(name)}function setViewport(el,width){document.querySelectorAll('.vp-btn').forEach(b=>b.classList.remove('active'));el.classList.add('active');const app=document.querySelector('#fullpreviewFrame .mock-fullscreen-app');if(app){if(width==='390px'){app.style.maxWidth='390px';app.style.height='700px'}else if(width==='768px'){app.style.maxWidth='768px';app.style.height='560px'}else{app.style.maxWidth='900px';app.style.height='500px'}}}
function openNewProject(){exitAgentMode();document.getElementById('newProjectModal').classList.add('open');setTimeout(()=>document.getElementById('newProjectName').focus(),100)}function closeNewProject(){document.getElementById('newProjectModal').classList.remove('open')}function selectType(el){document.querySelectorAll('.type-option').forEach(t=>t.classList.remove('active-type'));el.classList.add('active-type')}function insertChip(text){const ta=document.getElementById('promptInput');ta.value=ta.value.trimEnd()+(ta.value?', ':'')+text;ta.focus()}function redeploy(){showToast('Vercel deployment integration is coming next')}function restoreIter(){showToast('Restore will be available with the agent backend')}function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}function copyUrl(){const url=currentProject&&currentProject.deploy_url;if(!url){showToast('No deployment URL yet');return}navigator.clipboard?.writeText(url).catch(()=>{});showToast('URL copied')}function openUrl(){const url=currentProject&&currentProject.deploy_url;if(url)window.open(url,'_blank');else showToast('No deployment URL yet')}function toggleFullscreen(){showToast('Fullscreen preview is not available yet')}function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function formatDate(iso){const d=new Date(iso);const diff=(Date.now()-d.getTime())/1000;if(diff<60)return'Just now';if(diff<3600)return`${Math.floor(diff/60)} min ago`;if(diff<86400)return`${Math.floor(diff/3600)} h ago`;return d.toLocaleDateString('en-CA')}function formatTime(iso){if(!iso)return'';return new Date(iso).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}

document.addEventListener('keydown',e=>{const overlay=document.getElementById('authOverlay');const authVisible=overlay&&!overlay.classList.contains('hidden');const otpVisible=document.getElementById('otpFormView')&&!document.getElementById('otpFormView').classList.contains('hidden');if(e.key==='Escape'){exitAgentMode();closeNewProject()}if(e.key==='Enter'&&authVisible){if(otpVisible)verifyOtpCode();else submitAuth()}});document.addEventListener('input',e=>{if(e.target&&e.target.id==='otpCode'){e.target.value=e.target.value.replace(/\D/g,'').slice(0,6);if(e.target.value.length===6)verifyOtpCode()}});document.getElementById('newProjectModal').addEventListener('click',e=>{if(e.target===e.currentTarget)closeNewProject()});initAuth();setAuthMode('login')
